import type { Metadata } from 'next';
import './globals.css';
import { ReactNode } from 'react';
import { Provider } from 'jotai';

export const metadata: Metadata = {
  title: 'Thullo App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-custom-bg-color">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
